const competitionSeederData = [
    {
        date: '05-05-2024',
        location: 'Sportpark Overveer',
        homeTeam: 'Ajax',
        homeTeamLogo: 'ajax.png',
        awayTeam: 'Olympia',
        awayTeamLogo: 'olympia.png',
    },
    {
        date: '12-05-2024',
        location: 'Sportpark Nieuw Hanenburg',
        homeTeam: 'Quick',
        homeTeamLogo: 'quick.png',
        awayTeam: 'Ajax',
        awayTeamLogo: 'ajax.png',
    },
    {
        date: '19-05-2024',
        location: 'Sportpark Overveer',
        homeTeam: 'Ajax',
        homeTeamLogo: 'ajax.png',
        awayTeam: 'Qui Vive',
        awayTeamLogo: 'qui_vive.png',
    },
    {
        date: '26-05-2024',
        location: 'Sportpark Craeyenhout',
        homeTeam: 'HBS',
        homeTeamLogo: 'hbs.png',
        awayTeam: 'Ajax',
        awayTeamLogo: 'ajax.png',
    },
    {
        date: '02-06-2024',
        location: 'Sportpark Overveer',
        homeTeam: 'Ajax',
        homeTeamLogo: 'ajax.png',
        awayTeam: 'MOP',
        awayTeamLogo: 'mop.png',
    },
    {
        date: '23-06-2024',
        location: 'Sportpark Overveer',
        homeTeam: 'Ajax',
        homeTeamLogo: 'ajax.png',
        awayTeam: 'Quick',
        awayTeamLogo: 'quick.png',
    },
    {
        date: '30-06-2024',
        location: 'Sportpark Overveer',
        homeTeam: 'Ajax',
        homeTeamLogo: 'ajax.png',
        awayTeam: 'HBS',
        awayTeamLogo: 'hbs.png',
    },
    {
        date: '07-07-2024',
        location: 'Sportpark Begenshuizen',
        homeTeam: 'MOP',
        homeTeamLogo: 'mop.png',
        awayTeam: 'Ajax',
        awayTeamLogo: 'ajax.png',
    },
    {
        date: '04-08-2024',
        location: 'Groenhovenpark',
        homeTeam: 'Olympia',
        homeTeamLogo: 'olympia.png',
        awayTeam: 'Ajax',
        awayTeamLogo: 'ajax.png',
    },
    {
        date: '10-08-2024',
        location: 'Sportpark De Eendracht',
        homeTeam: 'Qui Vive',
        homeTeamLogo: 'qui_vive.png',
        awayTeam: 'Ajax',
        awayTeamLogo: 'ajax.png',
    },
    {
        date: '18-08-2024',
        location: 'Sportpark Overveer',
        homeTeam: 'Ajax',
        homeTeamLogo: 'ajax.png',
        awayTeam: 'Kampong',
        awayTeamLogo: 'kampong.png',
    },
    {
        date: '25-08-2024',
        location: 'Schiebroekse Park',
        homeTeam: 'VOC',
        homeTeamLogo: 'voc.png',
        awayTeam: 'Ajax',
        awayTeamLogo: 'ajax.png',
    }
]

export default competitionSeederData;